#cloud-config
users:
  - default
  - name: blockform
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - @@PUB_KEY@@
write_files:
  - owner: root:root
    path: /lib/systemd/system/geth.service
    content: |
        [Unit]
        Description=Geth
        After=network.target
        [Service]
        Type=simple
        Restart=always
        RestartSec=10
        User=blockform
        WorkingDirectory=/home/blockform
        StandardOutput=journal
        ExecStart=/usr/bin/geth --datadir /home/blockform/.ethereum --syncmode full --networkid @@NET_ID@@ --rpc --rpcapi net,eth,web3,personal --allow-insecure-unlock --rpcaddr 127.0.0.1 --rpcport 8445 --rpccorsdomain * --rpcvhosts * --ws --wsaddr 127.0.0.1 --wsport 8446 --wsorigins * --nodiscover --password /password.txt --unlock @@SEALER@@ --mine --etherbase @@SEALER@@
        [Install]
        WantedBy=multi-user.target
  - owner: root:root
    path: /genesis.json
    content: |
        {
          "config": {
            "chainId": @@NET_ID@@,
            "homesteadBlock": 1,
            "eip150Block": 2,
            "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
            "eip155Block": 3,
            "eip158Block": 3,
            "byzantiumBlock": 4,
            "clique": {
              "period": 15,
              "epoch": 30000
            }
          },
          "nonce": "0x0",
          "timestamp": "0x5bd95c94",
          "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000@@SEALER@@0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
          "gasLimit": "0x8000000",
          "difficulty": "0x1",
          "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "coinbase": "0x0000000000000000000000000000000000000000",
          "alloc": {
            "@@SEALER@@": {
              "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
            }
          },
          "number": "0x0",
          "gasUsed": "0x0",
          "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
        }
  - owner: root:root
    path: /usr/bin/faucet
    permissions: '0755'
    content: |
        #!/usr/bin/env perl
        use Dancer2;
        set port => 8080;
        get '/@@API_KEY@@/:addr' => sub {
          my $addr = route_parameters->get('addr');
          header 'Access-Control-Allow-Origin' => '*';
          return `/usr/bin/geth --exec "eth.sendTransaction({from:eth.coinbase, to:'${addr}', value: web3.toWei(1.0, 'ether'), gas:21000});" attach /home/blockform/.ethereum/geth.ipc`;
        };
        start;
  - owner: root:root
    path: /lib/systemd/system/faucet.service
    content: |
        [Unit]
        Description=Faucet
        After=network.target
        [Service]
        Type=simple
        Restart=always
        RestartSec=10
        User=blockform
        WorkingDirectory=/home/blockform
        StandardOutput=journal
        ExecStart=/usr/bin/faucet
        [Install]
        WantedBy=multi-user.target
  - owner: root:root
    path: /etc/nginx/sites-available/default
    content: |
        server {
          listen 8545;
          error_log syslog:server=unix:/dev/log;
          access_log syslog:server=unix:/dev/log;
          location /@@API_KEY@@ {
            proxy_pass http://127.0.0.1:8445;
          }
        }
        server {
          listen 8546;
          error_log syslog:server=unix:/dev/log;
          access_log syslog:server=unix:/dev/log;
          location /@@API_KEY@@ {
            proxy_pass http://127.0.0.1:8446;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
          }
        }
  - owner: root:root
    path: /etc/blockform
    content: |
        SITE_URL="@@SITE_URL@@"
        NODE_ID=@@NODE_ID@@
        API_KEY="@@API_KEY@@"
packages:
  - nginx
  - curl
  - git
  - python-certbot-nginx
  - libdancer2-perl
  - ufw
  - fail2ban
runcmd:
  - chown -R blockform:blockform /home/blockform/.ethereum
  - wget -q @@GETH_URL@@
  - tar xf geth-linux-*.tar.gz
  - cp geth-linux-*/geth /usr/bin/geth
  - echo "dummy" > /password.txt
  - '\geth --datadir /home/blockform/.ethereum --password /password.txt account new | sed "s/Address: {\(.*\)}/\1/g" > /sealer'
  - cat /genesis.json | sed "s/@@SEALER@@/`cat /sealer`/g" > /genesis.json
  - cat /lib/systemd/system/geth.service | sed "s/@@SEALER@@/`cat /sealer`/g" > /lib/systemd/system/geth.service
  - geth --nodiscover --datadir /home/blockform/.ethereum init /genesis.json
  - systemctl enable geth
  - systemctl start geth
  - systemctl enable faucet
  - systemctl start faucet
  - systemctl restart nginx
  - ufw default allow outgoing
  - ufw default deny incoming
  - ufw allow 22
  - ufw allow 80
  - ufw allow 8080
  - ufw allow 8545
  - ufw allow 8546
  - ufw allow 30303
  - systemctl enable ufw
  - systemctl start ufw
  - systemctl enable fail2ban
  - systemctl start fail2ban
