#cloud-config
apt_sources:
  - source: "ppa:certbot/certbot"
package_upgrade: true
packages:
  - nginx
  - python-certbot-nginx
users:
  - default
  - name: blockform
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - @@PUB_KEY@@
disk_setup:
  @@DEVICE@@:
    table_type: 'mbr'
    layout: [100]
    overwrite: true
fs_setup:
  - label: data
    filesystem: 'ext4'
    device: '@@DEVICE@@'
    partition: auto
    overwrite: true
mounts:
  - [ "@@DEVICE@@1", "/datadrive", "ext4", "defaults", "0", "2" ]
write_files:
  - owner: root:root
  - path: /lib/systemd/system/geth.service
    content: |
        [Unit]
        Description=Geth
        After=network.target
        [Service]
        Type=simple
        Restart=always
        RestartSec=10
        User=blockform
        WorkingDirectory=/home/blockform
        StandardOutput=journal
        ExecStart=/usr/bin/geth --datadir /datadrive --syncmode fast --networkid 1 --rpc --rpcapi net,eth,web3,personal --rpcaddr 127.0.0.1 --rpcport 8445 --rpccorsdomain * --rpcvhosts *
        [Install]
        WantedBy=multi-user.target
  - owner: root:root
    path: /etc/nginx/sites-available/default
    content: |
        server {
          listen 8545;
          location /@@API_KEY@@ {
            proxy_pass http://127.0.0.1:8445;
          }
        }
  - owner: root:root
    path: /etc/cron.d/letsencrypt_renew
    content: "15 3 * * * /usr/bin/certbot renew --quiet"
runcmd:
  - chown -R blockform:blockform /datadrive
  - wget -q https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.13-225171a4.tar.gz
  - tar xf geth-linux-amd64-1.8.13-225171a4.tar.gz
  - cp geth-linux-amd64-1.8.13-225171a4/geth /usr/bin/geth
  - chown -R blockform:blockform /datadrive
  - systemctl enable geth
  - systemctl start geth
  - bash -c 'if [ "@@DOMAIN@@" == "" ]; then echo $(curl -s http://169.254.169.254/latest/meta-data/public-hostname) > /etc/domain; else echo "@@DOMAIN@@" > /etc/domain; fi;'
  - export DOMAIN=$(cat /etc/domain)
  - certbot certonly --nginx -d $DOMAIN --agree-tos --non-interactive --email jean@wetrust.io
  - sed -i -e "s|listen 8545;|server_name ${DOMAIN};listen [::]:8545 ssl ipv6only=on;listen 8545 ssl;ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;include /etc/letsencrypt/options-ssl-nginx.conf;ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;|g" /etc/nginx/sites-available/default
  - systemctl restart nginx
  - chown -R blockform:blockform /datadrive
