#cloud-config
package_upgrade: true
users:
  - default
  - name: blockform
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - @@PUB_KEY@@
disk_setup:
  @@DEVICE@@:
    table_type: 'mbr'
    layout: [100]
    overwrite: true
fs_setup:
  - label: data
    filesystem: 'ext4'
    device: '@@DEVICE@@'
    partition: auto
    overwrite: true
mounts:
  - [ "@@DEVICE@@1", "/datadrive", "ext4", "defaults", "0", "2" ]
write_files:
  - owner: root:root
    path: /lib/systemd/system/geth.service
    content: |
        [Unit]
        Description=Geth
        After=network.target
        [Service]
        Type=simple
        Restart=always
        RestartSec=10
        User=blockform
        WorkingDirectory=/home/blockform
        StandardOutput=journal
        ExecStart=/usr/bin/geth --datadir /datadrive --syncmode fast --networkid 3 --rpc --rpcapi net,eth,web3,personal --rpcaddr 127.0.0.1 --rpcport 8445 --rpccorsdomain * --rpcvhosts *
        [Install]
        WantedBy=multi-user.target
  - owner: root:root
    path: /etc/security/limits.conf
    content: |
        *    soft nofile 1048576
        *    hard nofile 1048576
        root soft nofile 1048576
        root hard nofile 1048576
  - owner: root:root
    path: /etc/pam.d/common-session
    content: |
        session [default=1] pam_permit.so
        session requisite   pam_deny.so
        session required    pam_permit.so
        session optional    pam_umask.so
        session required    pam_unix.so
        session optional    pam_systemd.so
        session required    pam_limits.so
  - owner: root:root
    path: /etc/sysctl.conf
    content: |
        fs.file-max = 2097152
        fs.nr_open = 1048576
        net.ipv4.netfilter.ip_conntrack_max = 1048576
        net.nf_conntrack_max = 1048576
        net.core.somaxconn = 1048576
  - owner: root:root
    path: /etc/systemd/system/nginx.service.d/limit.conf
    content: |
        [Service]
        LimitNOFILE=65536
  - owner: root:root
    path: /etc/nginx/nginx.conf
    content: |
        user www-data;
        worker_processes auto;
        pid /run/nginx.pid;
        worker_rlimit_nofile 65536;

        events {
          worker_connections 4096;
          multi_accept on;
        }

        http {
          tcp_nopush on;
          tcp_nodelay on;
          reset_timedout_connection on;
          keepalive_timeout 30;
          client_body_timeout 10;
          send_timeout 2;

          server {
            listen 8545;
            location /@@API_KEY@@ {
              proxy_pass http://127.0.0.1:8445;
            }
          }
        }
packages:
  - nginx
runcmd:
  - chown -R blockform:blockform /datadrive
  - wget -q https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.8.13-225171a4.tar.gz
  - tar xf geth-linux-amd64-1.8.13-225171a4.tar.gz
  - cp geth-linux-amd64-1.8.13-225171a4/geth /usr/bin/geth
  - chown -R blockform:blockform /datadrive
  - systemctl daemon-reload
  - systemctl enable geth
  - systemctl start geth
  - systemctl restart nginx
  - chown -R blockform:blockform /datadrive
